CREATE TABLE Person (
                        person_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        fullName varchar(100) NOT NULL UNIQUE,
                        yearOfBirth int NOT NULL
);

CREATE TABLE Book (
                      book_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title varchar(100) NOT NULL,
                      author varchar(100) NOT NULL,
                      year int NOT NULL,
                      person_id int REFERENCES Person(person_id) ON DELETE SET NULL
);